// <auto-generated />
using System;
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterAPIContext))]
    [Migration("20200821202628_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterAPI.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<bool>("Adopted");

                    b.Property<DateTime>("AdoptionDate");

                    b.Property<double>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Coloring");

                    b.Property<string>("Name");

                    b.Property<int>("Personality");

                    b.Property<int>("Sex");

                    b.Property<double>("Weight");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 249017,
                            About = "Love Cheek and Chin Scratches!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 2.0,
                            Breed = "Domestic Medium Hair",
                            Coloring = "Black",
                            Name = "Domino",
                            Personality = 3,
                            Sex = 0,
                            Weight = 11.800000000000001
                        },
                        new
                        {
                            CatId = 249281,
                            About = "Always PURRing and PURRfect!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 0.29999999999999999,
                            Breed = "Domestic Short Hair",
                            Coloring = "Brown Tabby",
                            Name = "Doug",
                            Personality = 4,
                            Sex = 0,
                            Weight = 5.2000000000000002
                        },
                        new
                        {
                            CatId = 249318,
                            About = "Anxious around new animals and people, but very sweet!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 2.0,
                            Breed = "Domestic Short Hair",
                            Coloring = "Blue Tabby",
                            Name = "Bunny",
                            Personality = 5,
                            Sex = 0,
                            Weight = 7.4000000000000004
                        });
                });

            modelBuilder.Entity("AnimalShelterAPI.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<bool>("Adopted");

                    b.Property<DateTime>("AdoptionDate");

                    b.Property<double>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Coloring");

                    b.Property<string>("Name");

                    b.Property<int>("Personality");

                    b.Property<int>("Sex");

                    b.Property<double>("Weight");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 248680,
                            About = "Playful biter, loves chassing rabbits!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 7.0,
                            Breed = "Labrador",
                            Coloring = "Yellow",
                            Name = "Angus",
                            Personality = 6,
                            Sex = 0,
                            Weight = 101.3
                        },
                        new
                        {
                            DogId = 227248,
                            About = "A true HomeBuddy! Knows many tricks and is a quick learner!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 1.8999999999999999,
                            Breed = "American Pit Bull - Australian Shepherd",
                            Coloring = "White Brown",
                            Name = "Penny",
                            Personality = 1,
                            Sex = 1,
                            Weight = 52.100000000000001
                        },
                        new
                        {
                            DogId = 249396,
                            About = "Love to Learn and Love to Cuddle. Netflix and Chill?",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 1.5,
                            Breed = "Dachsund",
                            Coloring = "Red White",
                            Name = "Churro",
                            Personality = 0,
                            Sex = 0,
                            Weight = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
